language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.7
    packages:
      - clang-3.7

install:
  - pip install pep8 lit

script:
  - lit -v tests
  - python setup.py check
  - python setup.py install
  - python setup.py sdist

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c3b71470714f6eaa03bc
    on_success: change
    on_failure: always
    on_start: never
