language: python

matrix:
  include:
    - os: linux
      sudo: false
      python: 2.7
    - os: linux
      sudo: false
      python: 3.2
    - os: linux
      sudo: false
      python: 3.3
    - os: linux
      sudo: false
      python: 3.4
    - os: linux
      sudo: false
      python: 3.5
    - os: linux
      sudo: false
      python: "pypy"
    - os: linux
      sudo: required
      dist: trusty
      python: 2.7
    - os: osx
      osx_image: xcode6.1
      language: generic
    - os: osx
      osx_image: xcode6.4
      language: generic
    - os: osx
      osx_image: xcode7.3
      language: generic
    - os: osx
      osx_image: xcode8
      language: generic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.7
    packages:
      - clang-3.7

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update;            fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python;    fi

install:
  - pip install -r test-requirements.txt

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then csrutil status || true; fi
  - uname
  - lit -v tests
  - python setup.py check
  - python setup.py install
  - python setup.py sdist

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c3b71470714f6eaa03bc
    on_success: change
    on_failure: always
    on_start: never
